services:
  app:
    container_name: gaffclant.dev
    image: gaffclant.dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - /etc/ssl/:/etc/ssl
